[package]
name = "map2fig"
version = "0.1.0"
edition = "2024"

[dependencies]
cdshealpix = "0.7"
image = "0.24.9"
imageproc = "0.23.0"
rusttype = "0.9"
fitsrs = "0.4.1"
rand = "0.8"
clap = { version = "4", features = ["derive"] }
cairo-rs = { version = "0.19", features = ["pdf"] }
sha2 = "0.10"
tempfile = "3"
directories = "5.0"
rayon = "1.10"

[features]
debug_overlay = []

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
